# Generated by Django 2.2.5 on 2020-12-24 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_connection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('database_type', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=15)),
                ('connection_name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('database', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('tables', models.CharField(max_length=10000)),
                ('connection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='D_A_T.user_connection')),
            ],
        ),
        migrations.CreateModel(
            name='user_query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=200)),
                ('check_name', models.CharField(max_length=200)),
                ('check_description', models.CharField(max_length=1000)),
                ('query_date', models.CharField(max_length=50)),
                ('connection_id', models.CharField(max_length=1000)),
                ('db_name', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(max_length=1000)),
                ('note_date', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
