from django.contrib import admin
from django.urls import path, include
import D_A_T.views

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', D_A_T.views.login , name='index'),
    path('db_connection', D_A_T.views.db_connection , name='db_connection'),
    path('databases', D_A_T.views.db_connection_controller , name='databases'),
    path('tables', D_A_T.views.tables_connection, name='tables'),
    path('form', D_A_T.views.form , name='form'),
    path('file', D_A_T.views.file , name='file'),
    path('get_checks',D_A_T.views.apply_checks, name = 'get_checks'),
    path('display_template', D_A_T.views.display_editable_tables, name='display_template'),
    path('csv_check', D_A_T.views.csv_clean, name='csv_checks'),
    path('display_results', D_A_T.views.db_checks, name='display_results'),
    path('dashboard', D_A_T.views.login_controller, name='dashboard'),
    path('logout', D_A_T.views.logout, name='logout'),
    path('home', D_A_T.views.index, name='home'),
    path('test_cases', D_A_T.views.test_cases, name='test_cases'),
    path('statistics', D_A_T.views.statistics, name='statistics'),
    path('statistics_table',D_A_T.views.statistics_table, name='statistics_table'),
    path('save_template',D_A_T.views.save_template, name='save_template'),
    path('statistics_visualization', D_A_T.views.charts, name='statistics_visualization'),
    path('actions',D_A_T.views.connection_action,name='actions'),
    path('save_note',D_A_T.views.save_note,name='save_note'),
    path('saved_template',D_A_T.views.save_csv,name='saved_template'),
    path('chart_shot', D_A_T.views.chart_shot, name='chart_shot'),
    path('edit_delete_notes', D_A_T.views.edit_delete_notes, name='edit_delete_notes'),
    path('columns_selection',D_A_T.views.columns_selection,name='columns_selection'),
    path('DQ_checks',D_A_T.views.create_dq_checks_template,name='DQ_checks'),
    path('table_of_results', D_A_T.views.table_of_results, name='table_of_results'),
    path('source_actions',D_A_T.views.source_actions,name='source_actions'),
    path('save_query',D_A_T.views.save_query,name='save_query'),
    path('dq_charts',D_A_T.views.dq_charts,name='dq_charts'),
    path('dq_charts_shot',D_A_T.views.dq_charts_shot,name='dq_charts_shot'),
    path('save_edited_source',D_A_T.views.save_edited_source,name='save_edited_source'),
    path('user_query', D_A_T.views.display_user_query, name='user_query'),
    path('rur_edit_delete_query', D_A_T.views.rur_edit_delete_query, name='rur_edit_delete_query'),
    path('save_edited_query', D_A_T.views.save_edited_query, name='save_edited_query'),
    path('check_doc', D_A_T.views.checks_document, name='check_doc'),
    path('support', D_A_T.views.support, name='support'),
    path('support_controller', D_A_T.views.support_controller, name='support_controller'),
    path('data_filter', D_A_T.views.data_filter, name='data_filter'),
    path('UDI_RENDER', D_A_T.views.UDI_Render, name='UDI_RENDER'),
    path('UDI_TRIGGER' , D_A_T.views.UDI_TRIGGER,name='UDI_TRIGGER'),
    path('UDI_Inputs' , D_A_T.views.UDI_inputs,name='UDI_INPUTS'),
    path('UDI_RENDERING_FROM_INPUTS' , D_A_T.views.UDI_RENDERING_FROM_INPUTS,name='UDI_RENDERING_FROM_INPUTS'),
    path('APIAutomation', D_A_T.views.APIAutomation, name='APIAutomation'),
    path('APIAutomationController',D_A_T.views.APIAutomationController,name='APIAutomationController'),
    path('UDIScripts',D_A_T.views.UDIScripts,name='UDIScripts'),
    path('UDI_Scripts_Renderer',D_A_T.views.UDI_Scripts_Renderer,name='UDI_Scripts_Renderer'),

]
